services:
  portal:
    container_name: acs-website-portal-staging
    image: ghcr.io/asc-base/acs-portal:staging-f737f643b3f50a3a903e93e5c8cf6cd6628e2e56
    restart: unless-stopped
    environment:
      API_URL: ${API_URL}
      NODE_ENV: staging
      # PORT: ${PORTAL_PORT}
    # depends_on:
    #   servers:
    #     condition: service_healthy
