services:
  portal:
    container_name: acs-website-portal-staging
    image: ghcr.io/asc-base/acs-portal:staging-245e75a1e2ad8456236d2e0e1cb4e5d6d0771f7e
    restart: unless-stopped
    environment:
      API_URL: ${API_URL}
      NODE_ENV: staging
      # PORT: ${PORTAL_PORT}
    # depends_on:
    #   servers:
    #     condition: service_healthy
