services:
  portal:
    container_name: acs-website-portal-staging
    image: ghcr.io/asc-base/acs-portal:staging-3f3c0e0bf678a32382b79749f1d0ab94b15b06c9
    restart: unless-stopped
    environment:
      API_URL: ${API_URL}
      NODE_ENV: staging
      # PORT: ${PORTAL_PORT}
    # depends_on:
    #   servers:
    #     condition: service_healthy
