services:
  database:
    image: postgres:18

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - acs-prod-network

    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  postgres-data:

networks:
  acs-prod-network:
    external: true
